/*
 * @Author: Always
 * @LastEditors: Always
 * @Date: 2020-10-23 14:57:17
 * @LastEditTime: 2020-10-27 14:57:38
 * @FilePath: /koala-frontend/src/store/constants/order.ts
 */

export const UPDATE_RETURN_OF_GOODS_MODAL_TYPE =
  'UPDATE_RETURN_OF_GOODS_MODAL_TYPE';
export const UPDATE_RETURN_OF_GOODS_MODAL_INFO =
  'UPDATE_RETURN_OF_GOODS_MODAL_INFO';

export const UPDATE_REFUND_COURIER_INFO_MODAL_TYPE =
  'UPDATE_REFUND_COURIER_INFO_MODAL_TYPE';
export const UPDATE_REFUND_COURIER_INFO_MODAL_INFO =
  'UPDATE_REFUND_COURIER_INFO_MODAL_INFO';
